### PR TITLE
Correcting typo mentioned by @pwnerzclub

### PR DESCRIPTION
**Pull request by willykaram**
Correcting typo in connection.ex mentioned in issue #5 by @pwnerzclub

### CODE REVIEW

**Comment by willykaram** [comment]
@pwnerzclub, _thanks_ for spotting the typo, I created a quick PR to help @hamiltop with this

**Comment by hamiltop** [comment]
Looks like the corrected line is already there (the next line) so I think we just need to remove the line with the typo.

**Comment by hamiltop** [comment]
My apologies for the terse response. I appreciate the help!

**Comment by hamiltop** [comment]
Took care of it.

**Pull request closed without merging**
